name: UI Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.11.0

    - name: Install dependencies
      run: yarn

    - name: Set environment variables
      run: |
        echo "REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}" > .env.local
        echo "REACT_APP_GOOGLE_MAPS_API_SMART=${{ secrets.REACT_APP_GOOGLE_MAPS_API_SMART }}" >> .env.local

    - name: Build
      run: yarn build

    - name: Deploy to Hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/
